doc::
	env PYTHONPATH=$(PYTHONPATH):../src/ python3 -m pydoc -w osmviz.manager
	env PYTHONPATH=$(PYTHONPATH):../src/ python3 -m pydoc -w osmviz.animation
	env PYTHONPATH=$(PYTHONPATH):../src/ python3 -m pydoc -w osmviz
